import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#383838',
  },
  background: {
    ...StyleSheet.absoluteFill,
    height: undefined,
    width: undefined,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  logo: {
    alignSelf: 'center',
    height: 120,
    marginBottom: 18,
    width: 190,
  },
  heading: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '700',
  },
  subtitle: {
    color: '#D5D5D5',
    fontSize: 16,
    marginBottom: 28,
    marginTop: 6,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    color: '#252525',
    fontSize: 16,
    height: 54,
    marginBottom: 14,
    paddingHorizontal: 16,
  },
  passwordWrapper: {
    position: 'relative',
  },
  passwordInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    color: '#252525',
    fontSize: 16,
    height: 54,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingRight: 88,
  },
  passwordToggle: {
    alignItems: 'center',
    height: 54,
    justifyContent: 'center',
    position: 'absolute',
    right: 12,
    top: 0,
    width: 68,
  },
  passwordToggleText: {
    color: '#8A651C',
    fontSize: 13,
    fontWeight: '700',
  },
  rememberRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 8,
    minHeight: 40,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: '#D5A23A',
    borderRadius: 4,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    marginRight: 10,
    width: 22,
  },
  checkboxSelected: {
    backgroundColor: '#D5A23A',
  },
  checkboxMark: {
    color: '#2B2520',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 18,
  },
  rememberText: {
    color: '#070707',
    fontSize: 14,
    backgroundColor: 'white',
    minHeight: 25,
    minWidth: 28,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#D5A23A',
    borderRadius: 10,
    height: 54,
    justifyContent: 'center',
    marginTop: 10,
  },
  primaryButtonText: {
    color: '#2B2520',
    fontSize: 17,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
    marginTop: 8,
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});